development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: playsay_development
  pool: 5
  username: postgres

demo:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: playsay_demo
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: playsay_test
  pool: 5
  username: postgres